version: '3'
services:
  app:
    image: trackman_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
    - APP_CONFIG_PATH=/data/config/config.json
    - USE_EMBEDDED_DB
    volumes:
    - ./config:/data/config
    external_links:
    - postgres
    depends_on:
    - mailhog
    - redis
  scheduler:
    image: trackman_app
    command: flask run-scheduler
    environment:
    - APP_CONFIG_PATH=/data/config/config.json
    - USE_EMBEDDED_DB
    volumes:
    - ./config:/data/config
    external_links:
    - postgres
    depends_on:
    - mailhog
    - redis
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
    - "9090:80"
    expose:
    - "9090"
    depends_on:
    - app
    volumes:
    - ./nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf
  redis:
    image: redis:4-alpine
    expose:
     - "6379"
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
    - "9025:8025"
