FROM python:3.11.2

# WARNING: Do not use this Dockerfile for production installs. It creates a
# temporary database that is stored in the container, which you definitely
# don't want for production.

RUN apt-get update \
        && apt-get install -y \
            git \
            libcap-dev \
            libjansson-dev \
            libpcre3-dev \
            libsasl2-dev \
            libyaml-dev \
            optipng \
            uuid-dev \
        && pip install --no-cache-dir pip-tools

RUN pip install --no-cache-dir uWSGI==2.0.20

WORKDIR /usr/src/app

# install python dependencies
COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /usr/src/app

EXPOSE 5000
ENV PYTHONPATH /usr/src/app
ENV FLASK_APP trackman
ENV USE_EMBEDDED_DB 1

# set permissions
RUN chown www-data:www-data trackman .

ENTRYPOINT ["/usr/src/app/entrypoint-dev.sh"]
CMD ["uwsgi" , "--ini", "uwsgi.ini:dev"]
