name: Build trackman-nginx Docker image and push to GitHub Container Registry
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish to GitHub Package Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: wuvt/trackman-nginx
        username: wuvt
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        dockerfile: nginx/Dockerfile
        tag_names: true
